// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xkhsbxlwbgipzutufjei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhraHNieGx3YmdpcHp1dHVmamVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODk0ODQsImV4cCI6MjA3NjY2NTQ4NH0.1txiNV8ELMEy757BcNRiYmJBdtn0zxdy2alhKN04Z5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);